### ISSUE TITLE
Capability of Robot Simulation

### ISSUE THREAD

**Issue by Danfoa** [open-dynamic-robot-initiative/open-dynamic-robot-initiative.github.io#5]
Good Day,

I would like to use this robot on my thesis project which I will be starting next semester. Initially, I would like to develop and test learning-based controllers on simulation. I cannot seem to find any simulation capability of the robot hardware, is there a unified URDF, or support for MuJoCo, PyBullet, or any other simulation framework? 

Thanks... very excited about the idea of using this robot for development

**Comment by jviereck** [comment]
Hi @Danfoa ,

thanks for your questions. We have a repo with all the properties of the robot including an URDF here:

  https://github.com/open-dynamic-robot-initiative/robot_properties_solo/

There is a class for using the robot from pybullet. You can find the class and how to use it here:

  https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/master/python/robot_properties_solo/quadruped12wrapper.py#L87

Please let me know in case you have any further questions.

Best,
Julian

**Comment by Danfoa** [comment]
Perfect, 

Thank you very much Julian, sorry for creating a new issue but I could not find this information in the documentation, nor the repo. 

Best,

Daniel

**Comment by jviereck** [comment]
Opening an issue for such cases is totally fine @Danfoa .
